export const furnaceHasRecipe: { [key: string]: Set<string> } = {
  "minecraft:furnace": new Set([
    // Vanilla
    "minecraft:acacia_leaves","minecraft:acacia_log","minecraft:acacia_wood","minecraft:ancient_debris","minecraft:azalea_leaves","minecraft:azalea_leaves_flowered","minecraft:basalt","minecraft:beef","minecraft:birch_leaves","minecraft:birch_log","minecraft:birch_wood","minecraft:black_terracotta","minecraft:blue_terracotta","minecraft:brown_terracotta","minecraft:cactus","minecraft:chainmail_boots","minecraft:chainmail_chestplate","minecraft:chainmail_helmet","minecraft:chainmail_leggings","minecraft:cherry_leaves","minecraft:cherry_log","minecraft:cherry_wood","minecraft:chicken","minecraft:chorus_fruit","minecraft:clay","minecraft:clay_ball","minecraft:coal_ore","minecraft:cobbled_deepslate","minecraft:cobblestone","minecraft:copper_axe","minecraft:copper_boots","minecraft:copper_chestplate","minecraft:copper_helmet","minecraft:copper_hoe","minecraft:copper_horse_armor","minecraft:copper_leggings","minecraft:copper_nautilus_armor","minecraft:copper_ore","minecraft:copper_pickaxe","minecraft:copper_shovel","minecraft:copper_spear","minecraft:copper_sword","minecraft:cyan_terracotta","minecraft:dark_oak_leaves","minecraft:dark_oak_log","minecraft:dark_oak_wood","minecraft:deepslate_bricks","minecraft:deepslate_coal_ore","minecraft:deepslate_copper_ore","minecraft:deepslate_diamond_ore","minecraft:deepslate_emerald_ore","minecraft:deepslate_gold_ore","minecraft:deepslate_iron_ore","minecraft:deepslate_lapis_ore","minecraft:deepslate_redstone_ore","minecraft:deepslate_tiles","minecraft:diamond_ore","minecraft:emerald_ore","minecraft:fish","minecraft:gold_ore","minecraft:golden_axe","minecraft:golden_boots","minecraft:golden_chestplate","minecraft:golden_helmet","minecraft:golden_hoe","minecraft:golden_horse_armor","minecraft:golden_leggings","minecraft:golden_nautilus_armor","minecraft:golden_pickaxe","minecraft:golden_shovel","minecraft:golden_spear","minecraft:golden_sword","minecraft:gray_terracotta","minecraft:green_terracotta","minecraft:iron_axe","minecraft:iron_boots","minecraft:iron_chestplate","minecraft:iron_helmet","minecraft:iron_hoe","minecraft:iron_horse_armor","minecraft:iron_leggings","minecraft:iron_nautilus_armor","minecraft:iron_ore","minecraft:iron_pickaxe","minecraft:iron_shovel","minecraft:iron_spear","minecraft:iron_sword","minecraft:jungle_leaves","minecraft:jungle_log","minecraft:jungle_wood","minecraft:kelp","minecraft:lapis_ore","minecraft:light_blue_terracotta","minecraft:light_gray_terracotta","minecraft:lime_terracotta","minecraft:magenta_terracotta","minecraft:mangrove_leaves","minecraft:mangrove_log","minecraft:mangrove_wood","minecraft:muttonRaw","minecraft:nether_brick","minecraft:nether_gold_ore","minecraft:netherrack","minecraft:oak_leaves","minecraft:oak_log","minecraft:oak_wood","minecraft:orange_terracotta","minecraft:pale_oak_leaves","minecraft:pale_oak_log","minecraft:pale_oak_wood","minecraft:pink_terracotta","minecraft:polished_blackstone_bricks","minecraft:porkchop","minecraft:potato","minecraft:purple_terracotta","minecraft:quartz_block","minecraft:quartz_ore","minecraft:rabbit","minecraft:raw_copper","minecraft:raw_gold","minecraft:raw_iron","minecraft:red_sand","minecraft:red_sandstone","minecraft:red_terracotta","minecraft:redstone_ore","minecraft:resin_clump","minecraft:salmon","minecraft:sand","minecraft:sandstone","minecraft:sea_pickle","minecraft:spruce_leaves","minecraft:spruce_log","minecraft:spruce_wood","minecraft:stone","minecraft:stone_bricks","minecraft:stripped_acacia_log","minecraft:stripped_acacia_wood","minecraft:stripped_birch_wood","minecraft:stripped_cherry_log","minecraft:stripped_cherry_wood","minecraft:stripped_dark_oak_log","minecraft:stripped_dark_oak_wood","minecraft:stripped_jungle_log","minecraft:stripped_jungle_wood","minecraft:stripped_mangrove_log","minecraft:stripped_mangrove_wood","minecraft:stripped_oak_log","minecraft:stripped_oak_wood","minecraft:stripped_pale_oak_log","minecraft:stripped_pale_oak_wood","minecraft:stripped_spruce_log","minecraft:stripped_spruce_wood","minecraft:wet_sponge","minecraft:white_terracotta","minecraft:yellow_terracotta",

    // Addons
    "cc:small_cactus","dbe:ajisa_log","dbe:deepslate_evolitium_ore","dbe:dirtstone_evolitium_ore","dbe:evolitium_ore","dbe:giant_fish","dbe:namek_stone_evolitium_ore","dbe:raw_dinosaur_meat","mbl_ts:bottle_of_water_dirty_1","mbl_ts:bottle_of_water_dirty_2","mbl_ts:bottle_of_water_dirty_3","mbl_ts:bottle_of_water_dirty_4","mbl_ts:empty_drink_tin","mbl_ts:empty_food_tin","mbl_ts:raw_aluminium","mbl_ts:raw_nickel","mbl_ts:raw_zinc","mc:centaur_meat","mc:leshy_leaves","mc:minitaur_meat","mcpe:pot_water","mcpe:raw_player","minecraft:bamboo_block","minecraft:black_stained_glass","minecraft:blue_egg","minecraft:blue_stained_glass","minecraft:brown_egg","minecraft:brown_stained_glass","minecraft:cyan_stained_glass","minecraft:egg","minecraft:glass","minecraft:green_stained_glass","minecraft:iron_ingot","minecraft:light_blue_stained_glass","minecraft:lime_stained_glass","minecraft:magenta_stained_glass","minecraft:nether_wart","minecraft:orange_stained_glass","minecraft:pink_stained_glass","minecraft:purple_stained_glass","minecraft:raw_copper_block","minecraft:raw_gold_block","minecraft:raw_iron_block","minecraft:red_stained_glass","minecraft:rotten_flesh","minecraft:soul_sand","minecraft:white_stained_glass","minecraft:yellow_stained_glass","pw:aluminum_ore","pw:empty_can","pw:raw_venison","ranzie:cooked_flesh","ranzie:raw_flesh","trenbankai:aluminum_ore","trenbankai:deepslate_aluminum_ore","trenbankai:steel_mix","utilitycraft:copper_dust","utilitycraft:energized_iron_dust","utilitycraft:gold_dust","utilitycraft:iron_dust","utilitycraft:netherite_dust","utilitycraft:netherite_scrap_dust","utilitycraft:raw_energized_iron","utilitycraft:raw_leather","utilitycraft:raw_steel","utilitycraft:raw_steel_block","utilitycraft:steel_dust"
  ]),
  "minecraft:blast_furnace": new Set([
    // Vanilla
    "minecraft:ancient_debris","minecraft:chainmail_boots","minecraft:chainmail_chestplate","minecraft:chainmail_helmet","minecraft:chainmail_leggings","minecraft:coal_ore","minecraft:copper_axe","minecraft:copper_boots","minecraft:copper_chestplate","minecraft:copper_helmet","minecraft:copper_hoe","minecraft:copper_horse_armor","minecraft:copper_leggings","minecraft:copper_nautilus_armor","minecraft:copper_ore","minecraft:copper_pickaxe","minecraft:copper_shovel","minecraft:copper_spear","minecraft:copper_sword","minecraft:deepslate_coal_ore","minecraft:deepslate_copper_ore","minecraft:deepslate_diamond_ore","minecraft:deepslate_emerald_ore","minecraft:deepslate_gold_ore","minecraft:deepslate_iron_ore","minecraft:deepslate_lapis_ore","minecraft:deepslate_redstone_ore","minecraft:diamond_ore","minecraft:emerald_ore","minecraft:gold_ore","minecraft:golden_axe","minecraft:golden_boots","minecraft:golden_chestplate","minecraft:golden_helmet","minecraft:golden_hoe","minecraft:golden_horse_armor","minecraft:golden_leggings","minecraft:golden_nautilus_armor","minecraft:golden_pickaxe","minecraft:golden_shovel","minecraft:golden_spear","minecraft:golden_sword","minecraft:iron_axe","minecraft:iron_boots","minecraft:iron_chestplate","minecraft:iron_helmet","minecraft:iron_hoe","minecraft:iron_horse_armor","minecraft:iron_leggings","minecraft:iron_nautilus_armor","minecraft:iron_ore","minecraft:iron_pickaxe","minecraft:iron_shovel","minecraft:iron_spear","minecraft:iron_sword","minecraft:lapis_ore","minecraft:nether_gold_ore","minecraft:quartz_ore","minecraft:raw_copper","minecraft:raw_gold","minecraft:raw_iron","minecraft:redstone_ore",

    // Addons
    "dbe:deepslate_evolitium_ore","dbe:dirtstone_evolitium_ore","dbe:evolitium_ore","dbe:namek_stone_evolitium_ore","mbl_ts:bottle_of_water_dirty_1","mbl_ts:bottle_of_water_dirty_2","mbl_ts:bottle_of_water_dirty_3","mbl_ts:bottle_of_water_dirty_4","mbl_ts:empty_drink_tin","mbl_ts:empty_food_tin","mbl_ts:raw_aluminium","mbl_ts:raw_nickel","mbl_ts:raw_zinc","mc:centaur_meat","mc:minitaur_meat","minecraft:black_stained_glass","minecraft:blue_stained_glass","minecraft:brown_stained_glass","minecraft:cyan_stained_glass","minecraft:glass","minecraft:green_stained_glass","minecraft:light_blue_stained_glass","minecraft:lime_stained_glass","minecraft:magenta_stained_glass","minecraft:nether_wart","minecraft:orange_stained_glass","minecraft:pink_stained_glass","minecraft:purple_stained_glass","minecraft:raw_copper_block","minecraft:raw_gold_block","minecraft:raw_iron_block","minecraft:red_stained_glass","minecraft:white_stained_glass","minecraft:yellow_stained_glass","pw:aluminum_ore","pw:empty_can","trenbankai:aluminum_ore","trenbankai:deepslate_aluminum_ore","trenbankai:steel_mix","utilitycraft:copper_dust","utilitycraft:energized_iron_dust","utilitycraft:gold_dust","utilitycraft:iron_dust","utilitycraft:netherite_dust","utilitycraft:netherite_scrap_dust","utilitycraft:raw_energized_iron","utilitycraft:raw_steel","utilitycraft:raw_steel_block","utilitycraft:steel_dust"
  ]),
  "minecraft:smoker": new Set([
    // Vanilla
    "minecraft:beef","minecraft:chicken","minecraft:fish","minecraft:kelp","minecraft:muttonRaw","minecraft:porkchop","minecraft:potato","minecraft:rabbit","minecraft:salmon",

    // Addons
    "dbe:giant_fish","dbe:raw_dinosaur_meat","mbl_ts:bottle_of_water_dirty_1","mbl_ts:bottle_of_water_dirty_2","mbl_ts:bottle_of_water_dirty_3","mbl_ts:bottle_of_water_dirty_4","mbl_ts:empty_drink_tin","mbl_ts:empty_food_tin","mc:centaur_meat","mc:minitaur_meat","mcpe:pot_water","mcpe:raw_player","minecraft:blue_egg","minecraft:brown_egg","minecraft:egg","minecraft:rotten_flesh","pw:raw_venison","ranzie:cooked_flesh","ranzie:raw_flesh"
  ])
}

export const furnaceRecipeList: { [key: string]: string | string[] } = {
  "minecraft:acacia_leaves": "minecraft:leaf_litter",
  "minecraft:acacia_log": "minecraft:charcoal",
  "minecraft:acacia_wood": "minecraft:charcoal",
  "minecraft:ancient_debris": "minecraft:netherite_scrap",
  "minecraft:azalea_leaves": "minecraft:leaf_litter",
  "minecraft:azalea_leaves_flowered": "minecraft:leaf_litter",
  "minecraft:basalt": "minecraft:smooth_basalt",
  "minecraft:beef": "minecraft:cooked_beef",
  "minecraft:birch_leaves": "minecraft:leaf_litter",
  "minecraft:birch_log": "minecraft:charcoal",
  "minecraft:birch_wood": "minecraft:charcoal",
  "minecraft:black_terracotta": "minecraft:black_glazed_terracotta",
  "minecraft:blue_terracotta": "minecraft:blue_glazed_terracotta",
  "minecraft:brown_terracotta": "minecraft:brown_glazed_terracotta",
  "minecraft:cactus": "minecraft:green_dye",
  "minecraft:chainmail_boots": "minecraft:iron_nugget",
  "minecraft:chainmail_chestplate": "minecraft:iron_nugget",
  "minecraft:chainmail_helmet": "minecraft:iron_nugget",
  "minecraft:chainmail_leggings": "minecraft:iron_nugget",
  "minecraft:cherry_leaves": "minecraft:leaf_litter",
  "minecraft:cherry_log": "minecraft:charcoal",
  "minecraft:cherry_wood": "minecraft:charcoal",
  "minecraft:chicken": "minecraft:cooked_chicken",
  "minecraft:chorus_fruit": "minecraft:chorus_fruit_popped",
  "minecraft:clay": "minecraft:hardened_clay",
  "minecraft:clay_ball": "minecraft:brick",
  "minecraft:coal_ore": "minecraft:coal",
  "minecraft:cobbled_deepslate": "minecraft:deepslate",
  "minecraft:cobblestone": "minecraft:stone",
  "minecraft:copper_axe": "minecraft:copper_nugget",
  "minecraft:copper_boots": "minecraft:copper_nugget",
  "minecraft:copper_chestplate": "minecraft:copper_nugget",
  "minecraft:copper_helmet": "minecraft:copper_nugget",
  "minecraft:copper_hoe": "minecraft:copper_nugget",
  "minecraft:copper_horse_armor": "minecraft:copper_nugget",
  "minecraft:copper_leggings": "minecraft:copper_nugget",
  "minecraft:copper_nautilus_armor": "minecraft:copper_nugget",
  "minecraft:copper_ore": "minecraft:copper_ingot",
  "minecraft:copper_pickaxe": "minecraft:copper_nugget",
  "minecraft:copper_shovel": "minecraft:copper_nugget",
  "minecraft:copper_spear": "minecraft:copper_nugget",
  "minecraft:copper_sword": "minecraft:copper_nugget",
  "minecraft:cyan_terracotta": "minecraft:cyan_glazed_terracotta",
  "minecraft:dark_oak_leaves": "minecraft:leaf_litter",
  "minecraft:dark_oak_log": "minecraft:charcoal",
  "minecraft:dark_oak_wood": "minecraft:charcoal",
  "minecraft:deepslate_bricks": "minecraft:cracked_deepslate_bricks",
  "minecraft:deepslate_coal_ore": "minecraft:coal",
  "minecraft:deepslate_copper_ore": "minecraft:copper_ingot",
  "minecraft:deepslate_diamond_ore": "minecraft:diamond",
  "minecraft:deepslate_emerald_ore": "minecraft:emerald",
  "minecraft:deepslate_gold_ore": "minecraft:gold_ingot",
  "minecraft:deepslate_iron_ore": "minecraft:iron_ingot",
  "minecraft:deepslate_lapis_ore": "minecraft:lapis_lazuli",
  "minecraft:deepslate_redstone_ore": "minecraft:redstone",
  "minecraft:deepslate_tiles": "minecraft:cracked_deepslate_tiles",
  "minecraft:diamond_ore": "minecraft:diamond",
  "minecraft:emerald_ore": "minecraft:emerald",
  "minecraft:fish": "minecraft:cooked_fish",
  "minecraft:gold_ore": "minecraft:gold_ingot",
  "minecraft:golden_axe": "minecraft:gold_nugget",
  "minecraft:golden_boots": "minecraft:gold_nugget",
  "minecraft:golden_chestplate": "minecraft:gold_nugget",
  "minecraft:golden_helmet": "minecraft:gold_nugget",
  "minecraft:golden_hoe": "minecraft:gold_nugget",
  "minecraft:golden_horse_armor": "minecraft:gold_nugget",
  "minecraft:golden_leggings": "minecraft:gold_nugget",
  "minecraft:golden_nautilus_armor": "minecraft:gold_nugget",
  "minecraft:golden_pickaxe": "minecraft:gold_nugget",
  "minecraft:golden_shovel": "minecraft:gold_nugget",
  "minecraft:golden_spear": "minecraft:gold_nugget",
  "minecraft:golden_sword": "minecraft:gold_nugget",
  "minecraft:gray_terracotta": "minecraft:gray_glazed_terracotta",
  "minecraft:green_terracotta": "minecraft:green_glazed_terracotta",
  "minecraft:iron_axe": "minecraft:iron_nugget",
  "minecraft:iron_boots": "minecraft:iron_nugget",
  "minecraft:iron_chestplate": "minecraft:iron_nugget",
  "minecraft:iron_helmet": "minecraft:iron_nugget",
  "minecraft:iron_hoe": "minecraft:iron_nugget",
  "minecraft:iron_horse_armor": "minecraft:iron_nugget",
  "minecraft:iron_leggings": "minecraft:iron_nugget",
  "minecraft:iron_nautilus_armor": "minecraft:iron_nugget",
  "minecraft:iron_ore": "minecraft:iron_ingot",
  "minecraft:iron_pickaxe": "minecraft:iron_nugget",
  "minecraft:iron_shovel": "minecraft:iron_nugget",
  "minecraft:iron_spear": "minecraft:iron_nugget",
  "minecraft:iron_sword": "minecraft:iron_nugget",
  "minecraft:jungle_leaves": "minecraft:leaf_litter",
  "minecraft:jungle_log": "minecraft:charcoal",
  "minecraft:jungle_wood": "minecraft:charcoal",
  "minecraft:kelp": "minecraft:dried_kelp",
  "minecraft:lapis_ore": "minecraft:lapis_lazuli",
  "minecraft:light_blue_terracotta": "minecraft:light_blue_glazed_terracotta",
  "minecraft:light_gray_terracotta": "minecraft:silver_glazed_terracotta",
  "minecraft:lime_terracotta": "minecraft:lime_glazed_terracotta",
  "minecraft:magenta_terracotta": "minecraft:magenta_glazed_terracotta",
  "minecraft:mangrove_leaves": "minecraft:leaf_litter",
  "minecraft:mangrove_log": "minecraft:charcoal",
  "minecraft:mangrove_wood": "minecraft:charcoal",
  "minecraft:muttonRaw": "minecraft:muttonCooked",
  "minecraft:nether_brick": "minecraft:cracked_nether_bricks",
  "minecraft:nether_gold_ore": "minecraft:gold_ingot",
  "minecraft:netherrack": "minecraft:netherbrick",
  "minecraft:oak_leaves": "minecraft:leaf_litter",
  "minecraft:oak_log": "minecraft:charcoal",
  "minecraft:oak_wood": "minecraft:charcoal",
  "minecraft:orange_terracotta": "minecraft:orange_glazed_terracotta",
  "minecraft:pale_oak_leaves": "minecraft:leaf_litter",
  "minecraft:pale_oak_log": "minecraft:charcoal",
  "minecraft:pale_oak_wood": "minecraft:charcoal",
  "minecraft:pink_terracotta": "minecraft:pink_glazed_terracotta",
  "minecraft:polished_blackstone_bricks": "minecraft:cracked_polished_blackstone_bricks",
  "minecraft:porkchop": "minecraft:cooked_porkchop",
  "minecraft:potato": "minecraft:baked_potato",
  "minecraft:purple_terracotta": "minecraft:purple_glazed_terracotta",
  "minecraft:quartz_block": "minecraft:smooth_quartz",
  "minecraft:quartz_ore": "minecraft:quartz",
  "minecraft:rabbit": "minecraft:cooked_rabbit",
  "minecraft:raw_copper": "minecraft:copper_ingot",
  "minecraft:raw_gold": "minecraft:gold_ingot",
  "minecraft:raw_iron": "minecraft:iron_ingot",
  "minecraft:red_sand": "minecraft:glass",
  "minecraft:red_sandstone": "minecraft:smooth_red_sandstone",
  "minecraft:red_terracotta": "minecraft:red_glazed_terracotta",
  "minecraft:redstone_ore": "minecraft:redstone",
  "minecraft:resin_clump": "minecraft:resin_brick",
  "minecraft:salmon": "minecraft:cooked_salmon",
  "minecraft:sand": "minecraft:glass",
  "minecraft:sandstone": "minecraft:smooth_sandstone",
  "minecraft:sea_pickle": "minecraft:lime_dye",
  "minecraft:spruce_leaves": "minecraft:leaf_litter",
  "minecraft:spruce_log": "minecraft:charcoal",
  "minecraft:spruce_wood": "minecraft:charcoal",
  "minecraft:stone": "minecraft:smooth_stone",
  "minecraft:stone_bricks": [
    "eidolon:smooth_stone_bricks",
    "minecraft:cracked_stone_bricks"
  ],
  "minecraft:stripped_acacia_log": "minecraft:charcoal",
  "minecraft:stripped_acacia_wood": "minecraft:charcoal",
  "minecraft:stripped_birch_wood": "minecraft:charcoal",
  "minecraft:stripped_cherry_log": "minecraft:charcoal",
  "minecraft:stripped_cherry_wood": "minecraft:charcoal",
  "minecraft:stripped_dark_oak_log": "minecraft:charcoal",
  "minecraft:stripped_dark_oak_wood": "minecraft:charcoal",
  "minecraft:stripped_jungle_log": "minecraft:charcoal",
  "minecraft:stripped_jungle_wood": "minecraft:charcoal",
  "minecraft:stripped_mangrove_log": "minecraft:charcoal",
  "minecraft:stripped_mangrove_wood": "minecraft:charcoal",
  "minecraft:stripped_oak_log": "minecraft:charcoal",
  "minecraft:stripped_oak_wood": "minecraft:charcoal",
  "minecraft:stripped_pale_oak_log": "minecraft:charcoal",
  "minecraft:stripped_pale_oak_wood": "minecraft:charcoal",
  "minecraft:stripped_spruce_log": "minecraft:charcoal",
  "minecraft:stripped_spruce_wood": "minecraft:charcoal",
  "minecraft:wet_sponge": "minecraft:sponge",
  "minecraft:white_terracotta": "minecraft:white_glazed_terracotta",
  "minecraft:yellow_terracotta": "minecraft:yellow_glazed_terracotta",

  // Addons
  "arena:raw_black_marble": "arena:fallen_marble",
  "arena:raw_marble": "arena:marble_fragment",
  "blayy:iron_plate": "blayy:steel_shard",
  "cc:small_cactus": "minecraft:green_dye",
  "dbe:ajisa_log": "minecraft:charcoal",
  "dbe:deepslate_evolitium_ore": "dbe:evolitium_crystal",
  "dbe:dirtstone_evolitium_ore": "dbe:evolitium_crystal",
  "dbe:evolitium_ore": "dbe:evolitium_crystal",
  "dbe:giant_fish": "dbe:cooked_giant_fish",
  "dbe:namek_stone_evolitium_ore": "dbe:evolitium_crystal",
  "dbe:raw_dinosaur_meat": "dbe:cooked_dinosaur_meat",
  "digital_miner:gold_dust": "minecraft:gold_ingot",
  "digital_miner:iron_dust": "minecraft:iron_ingot",
  "digital_miner:steel_dust": "digital_miner:steel_nugget",
  "eidolon:lead_ore": "eidolon:lead_ingot",
  "eidolon:pewter_blend": "eidolon:pewter_ingot",
  "korbon:chorus_log": "minecraft:charcoal",
  "korbon:chorus_wood": "minecraft:charcoal",
  "korbon:raw_jokle": "korbon:cooked_jokle",
  "korbon:stripped_chorus_log": "minecraft:charcoal",
  "korbon:stripped_chorus_wood": "minecraft:charcoal",
  "mbl_ts:bottle_of_water_dirty_1": "mbl_ts:bottle_of_water_1",
  "mbl_ts:bottle_of_water_dirty_2": "mbl_ts:bottle_of_water_2",
  "mbl_ts:bottle_of_water_dirty_3": "mbl_ts:bottle_of_water_3",
  "mbl_ts:bottle_of_water_dirty_4": "mbl_ts:bottle_of_water_4",
  "mbl_ts:empty_drink_tin": "minecraft:iron_nugget",
  "mbl_ts:empty_food_tin": "minecraft:iron_nugget",
  "mbl_ts:raw_aluminium": "mbl_ts:aluminium_ingot",
  "mbl_ts:raw_nickel": "mbl_ts:nickel_ingot",
  "mbl_ts:raw_zinc": "mbl_ts:zinc_ingot",
  "mc:centaur_meat": "mc:cooked_centaur_meat",
  "mc:leshy_leaves": "minecraft:leaf_litter",
  "mc:minitaur_meat": "mc:cooked_minitaur_meat",
  "mcpe:pot_water": "mcpe:pot_cook_water",
  "mcpe:raw_player": "mcpe:cooked_player",
  "minecraft:bamboo_block": "minecraft:charcoal",
  "minecraft:black_stained_glass": "mbl_ts:melted_glass",
  "minecraft:blue_egg": "bv:cooked_egg",
  "minecraft:blue_stained_glass": "mbl_ts:melted_glass",
  "minecraft:bone": "eidolon:enchanted_ash",
  "minecraft:brown_egg": "bv:cooked_egg",
  "minecraft:brown_stained_glass": "mbl_ts:melted_glass",
  "minecraft:cyan_stained_glass": "mbl_ts:melted_glass",
  "minecraft:egg": [
    "bv:cooked_egg",
    "oresplus:cooked_egg"
  ],
  "minecraft:glass": "mbl_ts:melted_glass",
  "minecraft:green_stained_glass": "mbl_ts:melted_glass",
  "minecraft:iron_ingot": "mbl_ts:unrefined_steel",
  "minecraft:light_blue_stained_glass": "mbl_ts:melted_glass",
  "minecraft:lime_stained_glass": "mbl_ts:melted_glass",
  "minecraft:magenta_stained_glass": "mbl_ts:melted_glass",
  "minecraft:nether_wart": "mbl_ts:dried_nether_wart",
  "minecraft:orange_stained_glass": "mbl_ts:melted_glass",
  "minecraft:pink_stained_glass": "mbl_ts:melted_glass",
  "minecraft:purple_stained_glass": "mbl_ts:melted_glass",
  "minecraft:raw_copper_block": "minecraft:copper_block",
  "minecraft:raw_gold_block": "minecraft:gold_block",
  "minecraft:raw_iron_block": "minecraft:iron_block",
  "minecraft:red_stained_glass": "mbl_ts:melted_glass",
  "minecraft:rotten_flesh": [
    "eidolon:tallow",
    "pw:cooked_flesh",
    "ranzie:raw_flesh",
    "trenbankai:cooked_flesh",
    "minecraft:leather"
  ],
  "minecraft:soul_sand": "morphing_bracelet:soul_glass",
  "minecraft:white_stained_glass": "mbl_ts:melted_glass",
  "minecraft:yellow_stained_glass": "mbl_ts:melted_glass",
  "more:cobalt_ore": "more:cobalt_ingot",
  "more:deepslate_cobalt_ore": "more:cobalt_ingot",
  "more:deepslate_jade_ore": "more:jade",
  "more:deepslate_ruby_ore": "more:ruby",
  "more:deepslate_titanium_ore": "more:titanium_ingot",
  "more:end_stardust_ore": "more:stardust",
  "more:jade_ore": "more:jade",
  "more:nether_ruby_ore": "more:ruby",
  "more:raw_cobalt": "more:cobalt_ingot",
  "more:raw_cobalt_block": "more:cobalt_block",
  "more:raw_jade": "more:jade",
  "more:raw_jade_block": "more:jade_block",
  "more:raw_titanium": "more:titanium_ingot",
  "more:raw_titanium_block": "more:titanium_block",
  "more:ruby_ore": "more:ruby",
  "more:sapphire_ore": "more:sapphire",
  "more:titanium_ore": "more:titanium_ingot",
  "oresplus:raw_cobalt": "oresplus:cobalt_ingot",
  "oresplus:raw_lead": "oresplus:lead_ingot",
  "oresplus:raw_palladium": "oresplus:palladium_ingot",
  "oresplus:raw_platinum": "platinum_ingot:netherite_ingot",
  "oresplus:raw_rose_gold": "oresplus:rose_gold_ingot",
  "oresplus:raw_silver": "oresplus:silver_ingot",
  "oresplus:raw_tane": "oresplus:tane_ingot",
  "oresplus:raw_titanium": "oresplus:titanium_ingot",
  "oresplus:raw_tungsten": "tungsten_ingot:netherite_ingot",
  "oresplus:silver_ore": "oresplus:silver_ingot",
  "pa:raw_rast_iron": "pa:tast_iron_ingot",
  "pa:raw_steel": "pa:steel_ingot",
  "pw:aluminum_ore": "pw:aluminum_ingot",
  "pw:empty_can": "pw:aluminum_ingot",
  "pw:raw_venison": "pw:cooked_venison",
  "ranzie:cooked_flesh": "minecraft:leather",
  "ranzie:raw_flesh": "ranzie:cooked_flesh",
  "trenbankai:aluminum_ore": "trenbankai:aluminum_ingot",
  "trenbankai:deepslate_aluminum_ore": "trenbankai:aluminum_ingot",
  "trenbankai:steel_mix": "trenbankai:steel_ingot",
  "um:coal_amethyst_shard": "minecraft:coal",
  "um:copper_amethyst_shard": "minecraft:copper_ingot",
  "um:diamond_amethyst_shard": "minecraft:diamond",
  "um:emerald_amethyst_shard": "minecraft:emerald",
  "um:gold_amethyst_shard": "minecraft:gold_ingot",
  "um:iron_amethyst_shard": "minecraft:iron_ingot",
  "um:nether_amethyst_shard": "minecraft:netherite_scrap",
  "um:quartz_amethyst_shard": "minecraft:quartz",
  "um:redstone_amethyst_shard": "minecraft:redstone",
  "um:utility_energized_iron_amethyst_shard": "utilitycraft:energized_iron_ingot",
  "um:utility_steel_amethyst_shard": "utilitycraft:steel_ingot",
  "utilitycraft:copper_dust": "minecraft:copper_ingot",
  "utilitycraft:energized_iron_dust": "utilitycraft:energized_iron_ingot",
  "utilitycraft:gold_dust": "minecraft:gold_ingot",
  "utilitycraft:iron_dust": "minecraft:iron_ingot",
  "utilitycraft:netherite_dust": "minecraft:netherite_ingot",
  "utilitycraft:netherite_scrap_dust": "minecraft:netherite_scrap",
  "utilitycraft:raw_energized_iron": "utilitycraft:energized_iron_ingot",
  "utilitycraft:raw_leather": "minecraft:leather",
  "utilitycraft:raw_steel": "utilitycraft:steel_ingot",
  "utilitycraft:raw_steel_block": "utilitycraft:steel_block",
  "utilitycraft:steel_dust": "utilitycraft:steel_ingot"
}